name: flutter_login_vk
description: Login via VK.com. Easily add VK login feature in your application. User profile information included.
version: 2.2.2+1
homepage: https://github.com/Innim/flutter_login_vk
repository: https://github.com/Innim/flutter_login_vk
issue_tracker: https://github.com/Innim/flutter_login_vk/issues

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  async: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  innim_lint: ^0.5.0+1

flutter:
  plugin:
    platforms:
      android:
        package: ru.innim.flutter_login_vk
        pluginClass: FlutterLoginVkPlugin
      ios:
        pluginClass: FlutterLoginVkPlugin
